version: "3.4"

services:
  sleeper:
    build:
      context: .
      target: sleeper
    ports:
      - "8080:8080"
    restart: on-failure
  test:
    build:
      context: .
      target: test
    environment:
#      REQUEST_STR: "http://httpbin.org/delay/5"
      REQUEST_STR: "http://sleeper:8080/?delay=5s"