version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint.exe run --fix
  test:
    cmds:
      - go test ./...
  bench:
    cmds:
      - cd skiplist && go test -bench=. -benchmem -benchtime=10000x
      - cd tree && go test -bench=. -benchmem -benchtime=10000x
      - cd test && go test -bench=. -benchmem -benchtime=100000x
